### ISSUE TITLE
empty kubernetes.ldif

### ISSUE THREAD

**Issue by floriankoch** [leanix/leanix-k8s-connector#38]
Hi, i run the connector (2.0.0-beta2) , and the generated kubernetes.ldif is empty
I see no error in the logs
Any hint how i can debug this?

**Comment by dan-leanix** [comment]
Hi,

the Helm Chart creates a ClusterRole and two ClusterRoleBindings. Therefore you need the correct permissions to create those resources.

You can check if you have the following ClusterRole and ClusterRoleBindings:

```
kubectl get clusterroles.rbac.authorization.k8s.io leanix-k8s-connector
kubectl get clusterrolebindings.rbac.authorization.k8s.io leanix-k8s-connector
kubectl get clusterrolebindings.rbac.authorization.k8s.io leanix-k8s-connector-view
```

**Comment by dan-leanix** [comment]
@floriankoch We identified the issue and will hopefully have a fix for it soon.

**Comment by floriankoch** [comment]
@dan-leanix  cool - looking forward

**Comment by dan-leanix** [comment]
@floriankoch Issue is fixed in version 2.0.0-beta3.

-> https://github.com/leanix/leanix-k8s-connector/releases/tag/2.0.0-beta3

**Comment by floriankoch** [comment]
now i got this error

`2020-04-29T00:04:45.762Z ▶ [CRIT] -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/runner/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.8.0/azblob/zc_storage_error.go
:42
===== RESPONSE ERROR (ServiceCode=InvalidBlobType) =====
Description=The blob type is invalid for this operation.
RequestId:a982fcd8-901e-0077-67b9-1d452d000000
Time:2020-04-29T00:04:45.7561540Z, Details:
   Code: InvalidBlobType
   PUT https://xxxxxx.blob.core.windows.net/dvagsandbox/kubernetes.ldif?timeout=61
   Authorization: REDACTED
   Content-Length: [21499382]
   User-Agent: [Azure-Storage/0.7 (go1.14.1; linux)]
   X-Ms-Blob-Cache-Control: []
   X-Ms-Blob-Content-Disposition: []
   X-Ms-Blob-Content-Encoding: []
   X-Ms-Blob-Content-Language: []
   X-Ms-Blob-Content-Type: []
   X-Ms-Blob-Type: [BlockBlob]
   X-Ms-Client-Request-Id: [df789ee5-47a8-4e66-7de5-05e5fea22e21]
   X-Ms-Date: [Wed, 29 Apr 2020 00:04:45 GMT]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 409 The blob type is invalid for this operation.
   Content-Length: [228]
   Content-Type: [application/xml]
   Date: [Wed, 29 Apr 2020 00:04:45 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [InvalidBlobType]
   X-Ms-Request-Id: [a982fcd8-901e-0077-67b9-1d452d000000]
   X-Ms-Version: [2018-11-09]`

**Comment by dan-leanix** [comment]
@floriankoch As written in the note for the release you need to delete the append blobs.

> NOTE: Delete all existing append blobs in the container in Azure Storage, you specified for the LDIF and log file upload. Otherwise the connector run throws an error, as append blobs cannot be overwritten with block blobs.

**Comment by floriankoch** [comment]
@dan-leanix  ah missed this, sry

**Comment by dan-leanix** [comment]
No problem.

**Comment by floriankoch** [comment]
works now :) thx
